######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 6 17:07:51 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MazeMap.h MazePerson.h MyMazeMap.H MyMazer.H Public.H
SOURCES += maze.cpp MazeMap.cpp MazePerson.cpp MyMazeMap.cpp MyMazer.cpp
